## Metadata

# 1. METADATA FILE
# Path to sample file
metadata: ./config/samplesheet.csv

# 2. GENOME REFERENCE INFORMATION
reference:  
    # Path to reference genome in fasta format
    fasta: /fdb/igenomes/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa
    # Chromosome length
    idx: /fdb/igenomes/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/hg38.chrom.sizes
    # Genome size for macs2 callpeak
    gsize: hs

# 3. BOWTIE DATABASE    
bowtiedb: 
    # Path to bowtie2 database (set bowtie_db: None if a new db has to be generated)
    path: /fdb/igenomes/Homo_sapiens/UCSC/hg38/Sequence/Bowtie2Index

# 4. READ FILES
# Path to raw reads directory (fastq files) 
reads: data/reads
# Set paired to False if single-end reads are used
paired: True

# 5. TRIMMING
# Perform trimming [True, False]
trimming: True
# Path to trimming adapters file
adapters: data/adapters/adapters.fa

# 6. DUPLICATED READS
# Flag duplicated reads [True, False]
flag_dup: True

# 7. BIGWIG FILES
# Make bigwig files from bam files
    # bw_bin: --binSize = Size of the bins
    # bw_normalization: --normalizeUsing = [RPKM,CPM,BPM,RPGC,None]
    # bw_ignire_dup: --ignoreDuplicates
bw_bin: 50
bw_normalization: "BPM"
bw_ignore_dup: True
